POST http://localhost:3000/reports
content-type: application/json

{
  "make": "kia",
  "model": "seltos",
  "year": 2021,
  "mileage": 12000,
  "lng": 45,
  "lat": 45,
  "price": 18000
}


###Approve an existing report

PATCH http://localhost:3000/reports/27
content-type: application/json

{
  "approved": true
}


### Get an esitmate for an existing vehicle
GET http://localhost:3000/reports?make=kia&model=seltos&year=2022&lng=45&lat=45&mileage=10000