POST http://localhost:3000/reports
content-type: application/json

{
  "make": "ferrari",
  "model": "f12 superfast",
  "year": 2022,
  "mileage": 1000,
  "lng": 0,
  "lat": 0,
  "price": 100000
}


###Approve an existing report

PATCH http://localhost:3000/reports/16
content-type: application/json

{
  "approved": false
}